// Generated by rstantools.  Do not edit by hand.

/*
    geostan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    geostan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with geostan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_esf_count_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_esf_count");
    reader.add_event(1, 1, "include", "parts/priors.stan");
    reader.add_event(1, 0, "start", "parts/priors.stan");
    reader.add_event(32, 31, "end", "parts/priors.stan");
    reader.add_event(32, 2, "restart", "model_esf_count");
    reader.add_event(35, 5, "include", "parts/glm_data.stan");
    reader.add_event(35, 0, "start", "parts/glm_data.stan");
    reader.add_event(51, 16, "end", "parts/glm_data.stan");
    reader.add_event(51, 6, "restart", "model_esf_count");
    reader.add_event(51, 6, "include", "parts/esf_data.stan");
    reader.add_event(51, 0, "start", "parts/esf_data.stan");
    reader.add_event(57, 6, "end", "parts/esf_data.stan");
    reader.add_event(57, 7, "restart", "model_esf_count");
    reader.add_event(61, 11, "include", "parts/QR.stan");
    reader.add_event(61, 0, "start", "parts/QR.stan");
    reader.add_event(70, 9, "end", "parts/QR.stan");
    reader.add_event(70, 12, "restart", "model_esf_count");
    reader.add_event(73, 15, "include", "parts/esf_parameters.stan");
    reader.add_event(73, 0, "start", "parts/esf_parameters.stan");
    reader.add_event(79, 6, "end", "parts/esf_parameters.stan");
    reader.add_event(79, 16, "restart", "model_esf_count");
    reader.add_event(79, 16, "include", "parts/glm_parameters.stan");
    reader.add_event(79, 0, "start", "parts/glm_parameters.stan");
    reader.add_event(86, 7, "end", "parts/glm_parameters.stan");
    reader.add_event(86, 17, "restart", "model_esf_count");
    reader.add_event(89, 20, "include", "parts/esf_trans_params.stan");
    reader.add_event(89, 0, "start", "parts/esf_trans_params.stan");
    reader.add_event(111, 22, "end", "parts/esf_trans_params.stan");
    reader.add_event(111, 21, "restart", "model_esf_count");
    reader.add_event(114, 24, "include", "parts/glm_model.stan");
    reader.add_event(114, 0, "start", "parts/glm_model.stan");
    reader.add_event(123, 9, "end", "parts/glm_model.stan");
    reader.add_event(123, 25, "restart", "model_esf_count");
    reader.add_event(123, 25, "include", "parts/rhs_model.stan");
    reader.add_event(123, 0, "start", "parts/rhs_model.stan");
    reader.add_event(130, 7, "end", "parts/rhs_model.stan");
    reader.add_event(130, 26, "restart", "model_esf_count");
    reader.add_event(160, 54, "end", "model_esf_count");
    return reader;
}
template <typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__>
Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__, T3__, T4__, typename boost::math::tools::promote_args<T5__, T6__, T7__, T8__, typename boost::math::tools::promote_args<T9__>::type>::type>::type, Eigen::Dynamic, 1>
rhs_prior(const int& dev,
              const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& z,
              const T2__& aux1_global,
              const T3__& aux2_global,
              const Eigen::Matrix<T4__, Eigen::Dynamic, 1>& aux1_local,
              const Eigen::Matrix<T5__, Eigen::Dynamic, 1>& aux2_local,
              const T6__& caux,
              const T7__& scale_global,
              const T8__& slab_scale,
              const T9__& error_scale, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T1__, T2__, T3__, T4__, typename boost::math::tools::promote_args<T5__, T6__, T7__, T8__, typename boost::math::tools::promote_args<T9__>::type>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 16;
        local_scalar_t__ tau(DUMMY_VAR__);
        (void) tau;  // dummy to suppress unused var warning
        stan::math::initialize(tau, DUMMY_VAR__);
        stan::math::fill(tau, DUMMY_VAR__);
        stan::math::assign(tau,(((aux1_global * stan::math::sqrt(aux2_global)) * scale_global) * error_scale));
        current_statement_begin__ = 17;
        local_scalar_t__ c(DUMMY_VAR__);
        (void) c;  // dummy to suppress unused var warning
        stan::math::initialize(c, DUMMY_VAR__);
        stan::math::fill(c, DUMMY_VAR__);
        stan::math::assign(c,(slab_scale * stan::math::sqrt(caux)));
        current_statement_begin__ = 18;
        validate_non_negative_index("lambda", "dev", dev);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lambda(dev);
        stan::math::initialize(lambda, DUMMY_VAR__);
        stan::math::fill(lambda, DUMMY_VAR__);
        stan::math::assign(lambda,elt_multiply(aux1_local, stan::math::sqrt(aux2_local)));
        current_statement_begin__ = 19;
        validate_non_negative_index("lambda_tilde", "dev", dev);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lambda_tilde(dev);
        stan::math::initialize(lambda_tilde, DUMMY_VAR__);
        stan::math::fill(lambda_tilde, DUMMY_VAR__);
        stan::math::assign(lambda_tilde,stan::math::sqrt(elt_divide(multiply(pow(c, 2), square(lambda)), add(pow(c, 2), multiply(square(tau), square(lambda))))));
        current_statement_begin__ = 20;
        return stan::math::promote_scalar<fun_return_scalar_t__>(multiply(elt_multiply(z, lambda_tilde), tau));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct rhs_prior_functor__ {
    template <typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__, T3__, T4__, typename boost::math::tools::promote_args<T5__, T6__, T7__, T8__, typename boost::math::tools::promote_args<T9__>::type>::type>::type, Eigen::Dynamic, 1>
    operator()(const int& dev,
              const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& z,
              const T2__& aux1_global,
              const T3__& aux2_global,
              const Eigen::Matrix<T4__, Eigen::Dynamic, 1>& aux1_local,
              const Eigen::Matrix<T5__, Eigen::Dynamic, 1>& aux2_local,
              const T6__& caux,
              const T7__& scale_global,
              const T8__& slab_scale,
              const T9__& error_scale, std::ostream* pstream__) const {
        return rhs_prior(dev, z, aux1_global, aux2_global, aux1_local, aux2_local, caux, scale_global, slab_scale, error_scale, pstream__);
    }
};
template <bool propto, typename T0__>
typename boost::math::tools::promote_args<T0__>::type
icar_normal_lpdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& phi,
                     const int& N,
                     const std::vector<int>& node1,
                     const std::vector<int>& node2, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 28;
        return stan::math::promote_scalar<fun_return_scalar_t__>(((-(0.5) * dot_self(subtract(stan::model::rvalue(phi, stan::model::cons_list(stan::model::index_multi(node1), stan::model::nil_index_list()), "phi"), stan::model::rvalue(phi, stan::model::cons_list(stan::model::index_multi(node2), stan::model::nil_index_list()), "phi")))) + normal_log(sum(phi), 0, (0.001 * N))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T0__>
typename boost::math::tools::promote_args<T0__>::type
icar_normal_lpdf(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& phi,
                     const int& N,
                     const std::vector<int>& node1,
                     const std::vector<int>& node2, std::ostream* pstream__) {
    return icar_normal_lpdf<false>(phi,N,node1,node2, pstream__);
}
struct icar_normal_lpdf_functor__ {
    template <bool propto, typename T0__>
        typename boost::math::tools::promote_args<T0__>::type
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& phi,
                     const int& N,
                     const std::vector<int>& node1,
                     const std::vector<int>& node2, std::ostream* pstream__) const {
        return icar_normal_lpdf(phi, N, node1, node2, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_esf_count
  : public stan::model::model_base_crtp<model_esf_count> {
private:
        int is_student;
        int has_sigma;
        int n;
        int dx;
        matrix_d x;
        vector_d offset;
        int has_re;
        int n_ids;
        std::vector<int> id;
        vector_d alpha_prior;
        std::vector<row_vector_d> beta_prior;
        vector_d alpha_tau_prior;
        vector_d t_nu_prior;
        vector_d sigma_prior;
        int dev;
        matrix_d EV;
        double scale_global;
        double slab_scale;
        double slab_df;
        std::vector<int> y;
        matrix_d Q_ast;
        matrix_d R_ast;
        matrix_d R_inverse;
public:
    model_esf_count(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_esf_count(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_esf_count_namespace::model_esf_count";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 37;
            context__.validate_dims("data initialization", "is_student", "int", context__.to_vec());
            is_student = int(0);
            vals_i__ = context__.vals_i("is_student");
            pos__ = 0;
            is_student = vals_i__[pos__++];
            check_greater_or_equal(function__, "is_student", is_student, 0);
            check_less_or_equal(function__, "is_student", is_student, 1);
            current_statement_begin__ = 38;
            context__.validate_dims("data initialization", "has_sigma", "int", context__.to_vec());
            has_sigma = int(0);
            vals_i__ = context__.vals_i("has_sigma");
            pos__ = 0;
            has_sigma = vals_i__[pos__++];
            check_greater_or_equal(function__, "has_sigma", has_sigma, 0);
            check_less_or_equal(function__, "has_sigma", has_sigma, 1);
            current_statement_begin__ = 39;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 0);
            current_statement_begin__ = 40;
            context__.validate_dims("data initialization", "dx", "int", context__.to_vec());
            dx = int(0);
            vals_i__ = context__.vals_i("dx");
            pos__ = 0;
            dx = vals_i__[pos__++];
            check_greater_or_equal(function__, "dx", dx, 0);
            current_statement_begin__ = 41;
            validate_non_negative_index("x", "n", n);
            validate_non_negative_index("x", "dx", dx);
            context__.validate_dims("data initialization", "x", "matrix_d", context__.to_vec(n,dx));
            x = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n, dx);
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_j_2_max__ = dx;
            size_t x_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                    x(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 42;
            validate_non_negative_index("offset", "n", n);
            context__.validate_dims("data initialization", "offset", "vector_d", context__.to_vec(n));
            offset = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("offset");
            pos__ = 0;
            size_t offset_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < offset_j_1_max__; ++j_1__) {
                offset(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 43;
            context__.validate_dims("data initialization", "has_re", "int", context__.to_vec());
            has_re = int(0);
            vals_i__ = context__.vals_i("has_re");
            pos__ = 0;
            has_re = vals_i__[pos__++];
            check_greater_or_equal(function__, "has_re", has_re, 0);
            check_less_or_equal(function__, "has_re", has_re, 1);
            current_statement_begin__ = 44;
            context__.validate_dims("data initialization", "n_ids", "int", context__.to_vec());
            n_ids = int(0);
            vals_i__ = context__.vals_i("n_ids");
            pos__ = 0;
            n_ids = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_ids", n_ids, 0);
            current_statement_begin__ = 45;
            validate_non_negative_index("id", "n", n);
            context__.validate_dims("data initialization", "id", "int", context__.to_vec(n));
            id = std::vector<int>(n, int(0));
            vals_i__ = context__.vals_i("id");
            pos__ = 0;
            size_t id_k_0_max__ = n;
            for (size_t k_0__ = 0; k_0__ < id_k_0_max__; ++k_0__) {
                id[k_0__] = vals_i__[pos__++];
            }
            size_t id_i_0_max__ = n;
            for (size_t i_0__ = 0; i_0__ < id_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "id[i_0__]", id[i_0__], 0);
                check_less_or_equal(function__, "id[i_0__]", id[i_0__], n_ids);
            }
            current_statement_begin__ = 46;
            validate_non_negative_index("alpha_prior", "2", 2);
            context__.validate_dims("data initialization", "alpha_prior", "vector_d", context__.to_vec(2));
            alpha_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("alpha_prior");
            pos__ = 0;
            size_t alpha_prior_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < alpha_prior_j_1_max__; ++j_1__) {
                alpha_prior(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 47;
            validate_non_negative_index("beta_prior", "dx", dx);
            validate_non_negative_index("beta_prior", "2", 2);
            context__.validate_dims("data initialization", "beta_prior", "row_vector_d", context__.to_vec(2,dx));
            beta_prior = std::vector<Eigen::Matrix<double, 1, Eigen::Dynamic> >(2, Eigen::Matrix<double, 1, Eigen::Dynamic>(dx));
            vals_r__ = context__.vals_r("beta_prior");
            pos__ = 0;
            size_t beta_prior_j_1_max__ = dx;
            size_t beta_prior_k_0_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < beta_prior_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < beta_prior_k_0_max__; ++k_0__) {
                    beta_prior[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 48;
            validate_non_negative_index("alpha_tau_prior", "3", 3);
            context__.validate_dims("data initialization", "alpha_tau_prior", "vector_d", context__.to_vec(3));
            alpha_tau_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(3);
            vals_r__ = context__.vals_r("alpha_tau_prior");
            pos__ = 0;
            size_t alpha_tau_prior_j_1_max__ = 3;
            for (size_t j_1__ = 0; j_1__ < alpha_tau_prior_j_1_max__; ++j_1__) {
                alpha_tau_prior(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 49;
            validate_non_negative_index("t_nu_prior", "2", 2);
            context__.validate_dims("data initialization", "t_nu_prior", "vector_d", context__.to_vec(2));
            t_nu_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("t_nu_prior");
            pos__ = 0;
            size_t t_nu_prior_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < t_nu_prior_j_1_max__; ++j_1__) {
                t_nu_prior(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 50;
            validate_non_negative_index("sigma_prior", "3", 3);
            context__.validate_dims("data initialization", "sigma_prior", "vector_d", context__.to_vec(3));
            sigma_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(3);
            vals_r__ = context__.vals_r("sigma_prior");
            pos__ = 0;
            size_t sigma_prior_j_1_max__ = 3;
            for (size_t j_1__ = 0; j_1__ < sigma_prior_j_1_max__; ++j_1__) {
                sigma_prior(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 53;
            context__.validate_dims("data initialization", "dev", "int", context__.to_vec());
            dev = int(0);
            vals_i__ = context__.vals_i("dev");
            pos__ = 0;
            dev = vals_i__[pos__++];
            check_greater_or_equal(function__, "dev", dev, 0);
            current_statement_begin__ = 54;
            validate_non_negative_index("EV", "n", n);
            validate_non_negative_index("EV", "dev", dev);
            context__.validate_dims("data initialization", "EV", "matrix_d", context__.to_vec(n,dev));
            EV = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n, dev);
            vals_r__ = context__.vals_r("EV");
            pos__ = 0;
            size_t EV_j_2_max__ = dev;
            size_t EV_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < EV_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < EV_j_1_max__; ++j_1__) {
                    EV(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 55;
            context__.validate_dims("data initialization", "scale_global", "double", context__.to_vec());
            scale_global = double(0);
            vals_r__ = context__.vals_r("scale_global");
            pos__ = 0;
            scale_global = vals_r__[pos__++];
            check_greater_or_equal(function__, "scale_global", scale_global, 0);
            current_statement_begin__ = 56;
            context__.validate_dims("data initialization", "slab_scale", "double", context__.to_vec());
            slab_scale = double(0);
            vals_r__ = context__.vals_r("slab_scale");
            pos__ = 0;
            slab_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "slab_scale", slab_scale, 0);
            current_statement_begin__ = 57;
            context__.validate_dims("data initialization", "slab_df", "double", context__.to_vec());
            slab_df = double(0);
            vals_r__ = context__.vals_r("slab_df");
            pos__ = 0;
            slab_df = vals_r__[pos__++];
            check_greater_or_equal(function__, "slab_df", slab_df, 0);
            current_statement_begin__ = 58;
            validate_non_negative_index("y", "n", n);
            context__.validate_dims("data initialization", "y", "int", context__.to_vec(n));
            y = std::vector<int>(n, int(0));
            vals_i__ = context__.vals_i("y");
            pos__ = 0;
            size_t y_k_0_max__ = n;
            for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                y[k_0__] = vals_i__[pos__++];
            }
            // initialize transformed data variables
            current_statement_begin__ = 62;
            validate_non_negative_index("Q_ast", "n", n);
            validate_non_negative_index("Q_ast", "dx", dx);
            Q_ast = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n, dx);
            stan::math::fill(Q_ast, DUMMY_VAR__);
            current_statement_begin__ = 63;
            validate_non_negative_index("R_ast", "dx", dx);
            validate_non_negative_index("R_ast", "dx", dx);
            R_ast = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(dx, dx);
            stan::math::fill(R_ast, DUMMY_VAR__);
            current_statement_begin__ = 64;
            validate_non_negative_index("R_inverse", "dx", dx);
            validate_non_negative_index("R_inverse", "dx", dx);
            R_inverse = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(dx, dx);
            stan::math::fill(R_inverse, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 65;
            if (as_bool(dx)) {
                current_statement_begin__ = 66;
                stan::math::assign(Q_ast, multiply(stan::model::rvalue(qr_Q(x), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_min_max(1, dx), stan::model::nil_index_list())), "qr_Q(x)"), stan::math::sqrt((n - 1))));
                current_statement_begin__ = 67;
                stan::math::assign(R_ast, divide(stan::model::rvalue(qr_R(x), stan::model::cons_list(stan::model::index_min_max(1, dx), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "qr_R(x)"), stan::math::sqrt((n - 1))));
                current_statement_begin__ = 68;
                stan::math::assign(R_inverse, inverse(R_ast));
            }
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 74;
            num_params_r__ += 1;
            current_statement_begin__ = 75;
            num_params_r__ += 1;
            current_statement_begin__ = 76;
            validate_non_negative_index("aux1_local", "dev", dev);
            num_params_r__ += dev;
            current_statement_begin__ = 77;
            validate_non_negative_index("aux2_local", "dev", dev);
            num_params_r__ += dev;
            current_statement_begin__ = 78;
            num_params_r__ += 1;
            current_statement_begin__ = 79;
            validate_non_negative_index("z", "dev", dev);
            num_params_r__ += dev;
            current_statement_begin__ = 80;
            num_params_r__ += 1;
            current_statement_begin__ = 81;
            validate_non_negative_index("beta_tilde", "dx", dx);
            num_params_r__ += dx;
            current_statement_begin__ = 82;
            validate_non_negative_index("alpha_re_tilde", "n_ids", n_ids);
            num_params_r__ += n_ids;
            current_statement_begin__ = 83;
            validate_non_negative_index("alpha_tau", "has_re", has_re);
            num_params_r__ += (1 * has_re);
            current_statement_begin__ = 84;
            validate_non_negative_index("nu", "is_student", is_student);
            num_params_r__ += (1 * is_student);
            current_statement_begin__ = 85;
            validate_non_negative_index("sigma", "has_sigma", has_sigma);
            num_params_r__ += (1 * has_sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_esf_count() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 74;
        if (!(context__.contains_r("aux1_global")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aux1_global missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aux1_global");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "aux1_global", "double", context__.to_vec());
        double aux1_global(0);
        aux1_global = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, aux1_global);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aux1_global: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 75;
        if (!(context__.contains_r("aux2_global")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aux2_global missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aux2_global");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "aux2_global", "double", context__.to_vec());
        double aux2_global(0);
        aux2_global = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, aux2_global);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aux2_global: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 76;
        if (!(context__.contains_r("aux1_local")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aux1_local missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aux1_local");
        pos__ = 0U;
        validate_non_negative_index("aux1_local", "dev", dev);
        context__.validate_dims("parameter initialization", "aux1_local", "vector_d", context__.to_vec(dev));
        Eigen::Matrix<double, Eigen::Dynamic, 1> aux1_local(dev);
        size_t aux1_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux1_local_j_1_max__; ++j_1__) {
            aux1_local(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, aux1_local);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aux1_local: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 77;
        if (!(context__.contains_r("aux2_local")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable aux2_local missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("aux2_local");
        pos__ = 0U;
        validate_non_negative_index("aux2_local", "dev", dev);
        context__.validate_dims("parameter initialization", "aux2_local", "vector_d", context__.to_vec(dev));
        Eigen::Matrix<double, Eigen::Dynamic, 1> aux2_local(dev);
        size_t aux2_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux2_local_j_1_max__; ++j_1__) {
            aux2_local(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, aux2_local);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable aux2_local: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 78;
        if (!(context__.contains_r("caux")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable caux missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("caux");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "caux", "double", context__.to_vec());
        double caux(0);
        caux = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, caux);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable caux: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 79;
        if (!(context__.contains_r("z")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable z missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("z");
        pos__ = 0U;
        validate_non_negative_index("z", "dev", dev);
        context__.validate_dims("parameter initialization", "z", "vector_d", context__.to_vec(dev));
        Eigen::Matrix<double, Eigen::Dynamic, 1> z(dev);
        size_t z_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < z_j_1_max__; ++j_1__) {
            z(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(z);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable z: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 80;
        if (!(context__.contains_r("intercept")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable intercept missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("intercept");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "intercept", "double", context__.to_vec());
        double intercept(0);
        intercept = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(intercept);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable intercept: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 81;
        if (!(context__.contains_r("beta_tilde")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_tilde missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_tilde");
        pos__ = 0U;
        validate_non_negative_index("beta_tilde", "dx", dx);
        context__.validate_dims("parameter initialization", "beta_tilde", "vector_d", context__.to_vec(dx));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_tilde(dx);
        size_t beta_tilde_j_1_max__ = dx;
        for (size_t j_1__ = 0; j_1__ < beta_tilde_j_1_max__; ++j_1__) {
            beta_tilde(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta_tilde);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_tilde: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 82;
        if (!(context__.contains_r("alpha_re_tilde")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha_re_tilde missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha_re_tilde");
        pos__ = 0U;
        validate_non_negative_index("alpha_re_tilde", "n_ids", n_ids);
        context__.validate_dims("parameter initialization", "alpha_re_tilde", "vector_d", context__.to_vec(n_ids));
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha_re_tilde(n_ids);
        size_t alpha_re_tilde_j_1_max__ = n_ids;
        for (size_t j_1__ = 0; j_1__ < alpha_re_tilde_j_1_max__; ++j_1__) {
            alpha_re_tilde(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(alpha_re_tilde);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha_re_tilde: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 83;
        if (!(context__.contains_r("alpha_tau")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha_tau missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha_tau");
        pos__ = 0U;
        validate_non_negative_index("alpha_tau", "has_re", has_re);
        context__.validate_dims("parameter initialization", "alpha_tau", "double", context__.to_vec(has_re));
        std::vector<double> alpha_tau(has_re, double(0));
        size_t alpha_tau_k_0_max__ = has_re;
        for (size_t k_0__ = 0; k_0__ < alpha_tau_k_0_max__; ++k_0__) {
            alpha_tau[k_0__] = vals_r__[pos__++];
        }
        size_t alpha_tau_i_0_max__ = has_re;
        for (size_t i_0__ = 0; i_0__ < alpha_tau_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, alpha_tau[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha_tau: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 84;
        if (!(context__.contains_r("nu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable nu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("nu");
        pos__ = 0U;
        validate_non_negative_index("nu", "is_student", is_student);
        context__.validate_dims("parameter initialization", "nu", "double", context__.to_vec(is_student));
        std::vector<double> nu(is_student, double(0));
        size_t nu_k_0_max__ = is_student;
        for (size_t k_0__ = 0; k_0__ < nu_k_0_max__; ++k_0__) {
            nu[k_0__] = vals_r__[pos__++];
        }
        size_t nu_i_0_max__ = is_student;
        for (size_t i_0__ = 0; i_0__ < nu_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, nu[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable nu: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 85;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        validate_non_negative_index("sigma", "has_sigma", has_sigma);
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec(has_sigma));
        std::vector<double> sigma(has_sigma, double(0));
        size_t sigma_k_0_max__ = has_sigma;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            sigma[k_0__] = vals_r__[pos__++];
        }
        size_t sigma_i_0_max__ = has_sigma;
        for (size_t i_0__ = 0; i_0__ < sigma_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, sigma[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 74;
            local_scalar_t__ aux1_global;
            (void) aux1_global;  // dummy to suppress unused var warning
            if (jacobian__)
                aux1_global = in__.scalar_lb_constrain(0, lp__);
            else
                aux1_global = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 75;
            local_scalar_t__ aux2_global;
            (void) aux2_global;  // dummy to suppress unused var warning
            if (jacobian__)
                aux2_global = in__.scalar_lb_constrain(0, lp__);
            else
                aux2_global = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 76;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aux1_local;
            (void) aux1_local;  // dummy to suppress unused var warning
            if (jacobian__)
                aux1_local = in__.vector_lb_constrain(0, dev, lp__);
            else
                aux1_local = in__.vector_lb_constrain(0, dev);
            current_statement_begin__ = 77;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> aux2_local;
            (void) aux2_local;  // dummy to suppress unused var warning
            if (jacobian__)
                aux2_local = in__.vector_lb_constrain(0, dev, lp__);
            else
                aux2_local = in__.vector_lb_constrain(0, dev);
            current_statement_begin__ = 78;
            local_scalar_t__ caux;
            (void) caux;  // dummy to suppress unused var warning
            if (jacobian__)
                caux = in__.scalar_lb_constrain(0, lp__);
            else
                caux = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 79;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> z;
            (void) z;  // dummy to suppress unused var warning
            if (jacobian__)
                z = in__.vector_constrain(dev, lp__);
            else
                z = in__.vector_constrain(dev);
            current_statement_begin__ = 80;
            local_scalar_t__ intercept;
            (void) intercept;  // dummy to suppress unused var warning
            if (jacobian__)
                intercept = in__.scalar_constrain(lp__);
            else
                intercept = in__.scalar_constrain();
            current_statement_begin__ = 81;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_tilde;
            (void) beta_tilde;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_tilde = in__.vector_constrain(dx, lp__);
            else
                beta_tilde = in__.vector_constrain(dx);
            current_statement_begin__ = 82;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> alpha_re_tilde;
            (void) alpha_re_tilde;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha_re_tilde = in__.vector_constrain(n_ids, lp__);
            else
                alpha_re_tilde = in__.vector_constrain(n_ids);
            current_statement_begin__ = 83;
            std::vector<local_scalar_t__> alpha_tau;
            size_t alpha_tau_d_0_max__ = has_re;
            alpha_tau.reserve(alpha_tau_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < alpha_tau_d_0_max__; ++d_0__) {
                if (jacobian__)
                    alpha_tau.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    alpha_tau.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 84;
            std::vector<local_scalar_t__> nu;
            size_t nu_d_0_max__ = is_student;
            nu.reserve(nu_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < nu_d_0_max__; ++d_0__) {
                if (jacobian__)
                    nu.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    nu.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 85;
            std::vector<local_scalar_t__> sigma;
            size_t sigma_d_0_max__ = has_sigma;
            sigma.reserve(sigma_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < sigma_d_0_max__; ++d_0__) {
                if (jacobian__)
                    sigma.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    sigma.push_back(in__.scalar_lb_constrain(0));
            }
            // transformed parameters
            current_statement_begin__ = 91;
            validate_non_negative_index("f", "n", n);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> f(n);
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            current_statement_begin__ = 92;
            validate_non_negative_index("beta", "dx", dx);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta(dx);
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            current_statement_begin__ = 93;
            validate_non_negative_index("beta_ev", "dev", dev);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_ev(dev);
            stan::math::initialize(beta_ev, DUMMY_VAR__);
            stan::math::fill(beta_ev, DUMMY_VAR__);
            current_statement_begin__ = 94;
            local_scalar_t__ error_scale;
            (void) error_scale;  // dummy to suppress unused var warning
            stan::math::initialize(error_scale, DUMMY_VAR__);
            stan::math::fill(error_scale, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 95;
            if (as_bool(has_sigma)) {
                current_statement_begin__ = 96;
                stan::math::assign(error_scale, get_base1(sigma, 1, "sigma", 1));
            } else {
                current_statement_begin__ = 98;
                stan::math::assign(error_scale, 1);
            }
            current_statement_begin__ = 100;
            stan::math::assign(beta_ev, rhs_prior(dev, z, aux1_global, aux2_global, aux1_local, aux2_local, caux, scale_global, slab_scale, error_scale, pstream__));
            current_statement_begin__ = 101;
            stan::math::assign(f, add(add(offset, intercept), multiply(EV, beta_ev)));
            current_statement_begin__ = 102;
            if (as_bool(dx)) {
                current_statement_begin__ = 103;
                stan::math::assign(f, add(f, multiply(Q_ast, beta_tilde)));
                current_statement_begin__ = 104;
                stan::math::assign(beta, multiply(R_inverse, beta_tilde));
            }
            current_statement_begin__ = 106;
            if (as_bool(has_re)) {
                current_statement_begin__ = 107;
                for (int i = 1; i <= n; ++i) {
                    current_statement_begin__ = 108;
                    stan::model::assign(f, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (stan::model::rvalue(f, stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), "f") + (get_base1(alpha_tau, has_re, "alpha_tau", 1) * get_base1(alpha_re_tilde, get_base1(id, i, "id", 1), "alpha_re_tilde", 1))), 
                                "assigning variable f");
                }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 91;
            size_t f_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(f(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: f" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable f: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 92;
            size_t beta_j_1_max__ = dx;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 93;
            size_t beta_ev_j_1_max__ = dev;
            for (size_t j_1__ = 0; j_1__ < beta_ev_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta_ev(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta_ev" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta_ev: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 94;
            if (stan::math::is_uninitialized(error_scale)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: error_scale";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable error_scale: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            // model body
            current_statement_begin__ = 116;
            lp_accum__.add(normal_log<propto__>(intercept, get_base1(alpha_prior, 1, "alpha_prior", 1), get_base1(alpha_prior, 2, "alpha_prior", 1)));
            current_statement_begin__ = 117;
            if (as_bool(dx)) {
                current_statement_begin__ = 117;
                lp_accum__.add(normal_log<propto__>(beta, get_base1(beta_prior, 1, "beta_prior", 1), get_base1(beta_prior, 2, "beta_prior", 1)));
            }
            current_statement_begin__ = 118;
            if (as_bool(has_sigma)) {
                current_statement_begin__ = 118;
                lp_accum__.add(student_t_log<propto__>(sigma, get_base1(sigma_prior, 1, "sigma_prior", 1), get_base1(sigma_prior, 2, "sigma_prior", 1), get_base1(sigma_prior, 3, "sigma_prior", 1)));
            }
            current_statement_begin__ = 119;
            if (as_bool(has_re)) {
                current_statement_begin__ = 120;
                lp_accum__.add(student_t_log<propto__>(get_base1(alpha_tau, has_re, "alpha_tau", 1), get_base1(alpha_tau_prior, 1, "alpha_tau_prior", 1), get_base1(alpha_tau_prior, 2, "alpha_tau_prior", 1), get_base1(alpha_tau_prior, 3, "alpha_tau_prior", 1)));
                current_statement_begin__ = 121;
                lp_accum__.add(std_normal_log<propto__>(alpha_re_tilde));
            }
            current_statement_begin__ = 124;
            lp_accum__.add(std_normal_log<propto__>(z));
            current_statement_begin__ = 125;
            lp_accum__.add(normal_log<propto__>(aux1_local, 0, 1));
            current_statement_begin__ = 126;
            lp_accum__.add(inv_gamma_log<propto__>(aux2_local, 0.5, 0.5));
            current_statement_begin__ = 127;
            lp_accum__.add(std_normal_log<propto__>(aux1_global));
            current_statement_begin__ = 128;
            lp_accum__.add(inv_gamma_log<propto__>(aux2_global, 0.5, 0.5));
            current_statement_begin__ = 129;
            lp_accum__.add(inv_gamma_log<propto__>(caux, (0.5 * slab_df), (0.5 * slab_df)));
            current_statement_begin__ = 131;
            lp_accum__.add(poisson_log_log<propto__>(y, f));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("aux1_global");
        names__.push_back("aux2_global");
        names__.push_back("aux1_local");
        names__.push_back("aux2_local");
        names__.push_back("caux");
        names__.push_back("z");
        names__.push_back("intercept");
        names__.push_back("beta_tilde");
        names__.push_back("alpha_re_tilde");
        names__.push_back("alpha_tau");
        names__.push_back("nu");
        names__.push_back("sigma");
        names__.push_back("f");
        names__.push_back("beta");
        names__.push_back("beta_ev");
        names__.push_back("error_scale");
        names__.push_back("yrep");
        names__.push_back("fitted");
        names__.push_back("esf");
        names__.push_back("residual");
        names__.push_back("log_lik");
        names__.push_back("alpha_re");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(dev);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(dev);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(dev);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(dx);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_ids);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(has_re);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(is_student);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(has_sigma);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(dx);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(dev);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_ids);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_esf_count_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double aux1_global = in__.scalar_lb_constrain(0);
        vars__.push_back(aux1_global);
        double aux2_global = in__.scalar_lb_constrain(0);
        vars__.push_back(aux2_global);
        Eigen::Matrix<double, Eigen::Dynamic, 1> aux1_local = in__.vector_lb_constrain(0, dev);
        size_t aux1_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux1_local_j_1_max__; ++j_1__) {
            vars__.push_back(aux1_local(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> aux2_local = in__.vector_lb_constrain(0, dev);
        size_t aux2_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux2_local_j_1_max__; ++j_1__) {
            vars__.push_back(aux2_local(j_1__));
        }
        double caux = in__.scalar_lb_constrain(0);
        vars__.push_back(caux);
        Eigen::Matrix<double, Eigen::Dynamic, 1> z = in__.vector_constrain(dev);
        size_t z_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < z_j_1_max__; ++j_1__) {
            vars__.push_back(z(j_1__));
        }
        double intercept = in__.scalar_constrain();
        vars__.push_back(intercept);
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_tilde = in__.vector_constrain(dx);
        size_t beta_tilde_j_1_max__ = dx;
        for (size_t j_1__ = 0; j_1__ < beta_tilde_j_1_max__; ++j_1__) {
            vars__.push_back(beta_tilde(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha_re_tilde = in__.vector_constrain(n_ids);
        size_t alpha_re_tilde_j_1_max__ = n_ids;
        for (size_t j_1__ = 0; j_1__ < alpha_re_tilde_j_1_max__; ++j_1__) {
            vars__.push_back(alpha_re_tilde(j_1__));
        }
        std::vector<double> alpha_tau;
        size_t alpha_tau_d_0_max__ = has_re;
        alpha_tau.reserve(alpha_tau_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < alpha_tau_d_0_max__; ++d_0__) {
            alpha_tau.push_back(in__.scalar_lb_constrain(0));
        }
        size_t alpha_tau_k_0_max__ = has_re;
        for (size_t k_0__ = 0; k_0__ < alpha_tau_k_0_max__; ++k_0__) {
            vars__.push_back(alpha_tau[k_0__]);
        }
        std::vector<double> nu;
        size_t nu_d_0_max__ = is_student;
        nu.reserve(nu_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < nu_d_0_max__; ++d_0__) {
            nu.push_back(in__.scalar_lb_constrain(0));
        }
        size_t nu_k_0_max__ = is_student;
        for (size_t k_0__ = 0; k_0__ < nu_k_0_max__; ++k_0__) {
            vars__.push_back(nu[k_0__]);
        }
        std::vector<double> sigma;
        size_t sigma_d_0_max__ = has_sigma;
        sigma.reserve(sigma_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < sigma_d_0_max__; ++d_0__) {
            sigma.push_back(in__.scalar_lb_constrain(0));
        }
        size_t sigma_k_0_max__ = has_sigma;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            vars__.push_back(sigma[k_0__]);
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 91;
            validate_non_negative_index("f", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> f(n);
            stan::math::initialize(f, DUMMY_VAR__);
            stan::math::fill(f, DUMMY_VAR__);
            current_statement_begin__ = 92;
            validate_non_negative_index("beta", "dx", dx);
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta(dx);
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            current_statement_begin__ = 93;
            validate_non_negative_index("beta_ev", "dev", dev);
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta_ev(dev);
            stan::math::initialize(beta_ev, DUMMY_VAR__);
            stan::math::fill(beta_ev, DUMMY_VAR__);
            current_statement_begin__ = 94;
            double error_scale;
            (void) error_scale;  // dummy to suppress unused var warning
            stan::math::initialize(error_scale, DUMMY_VAR__);
            stan::math::fill(error_scale, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 95;
            if (as_bool(has_sigma)) {
                current_statement_begin__ = 96;
                stan::math::assign(error_scale, get_base1(sigma, 1, "sigma", 1));
            } else {
                current_statement_begin__ = 98;
                stan::math::assign(error_scale, 1);
            }
            current_statement_begin__ = 100;
            stan::math::assign(beta_ev, rhs_prior(dev, z, aux1_global, aux2_global, aux1_local, aux2_local, caux, scale_global, slab_scale, error_scale, pstream__));
            current_statement_begin__ = 101;
            stan::math::assign(f, add(add(offset, intercept), multiply(EV, beta_ev)));
            current_statement_begin__ = 102;
            if (as_bool(dx)) {
                current_statement_begin__ = 103;
                stan::math::assign(f, add(f, multiply(Q_ast, beta_tilde)));
                current_statement_begin__ = 104;
                stan::math::assign(beta, multiply(R_inverse, beta_tilde));
            }
            current_statement_begin__ = 106;
            if (as_bool(has_re)) {
                current_statement_begin__ = 107;
                for (int i = 1; i <= n; ++i) {
                    current_statement_begin__ = 108;
                    stan::model::assign(f, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (stan::model::rvalue(f, stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), "f") + (get_base1(alpha_tau, has_re, "alpha_tau", 1) * get_base1(alpha_re_tilde, get_base1(id, i, "id", 1), "alpha_re_tilde", 1))), 
                                "assigning variable f");
                }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t f_j_1_max__ = n;
                for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                    vars__.push_back(f(j_1__));
                }
                size_t beta_j_1_max__ = dx;
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    vars__.push_back(beta(j_1__));
                }
                size_t beta_ev_j_1_max__ = dev;
                for (size_t j_1__ = 0; j_1__ < beta_ev_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_ev(j_1__));
                }
                vars__.push_back(error_scale);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 135;
            validate_non_negative_index("yrep", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> yrep(n);
            stan::math::initialize(yrep, DUMMY_VAR__);
            stan::math::fill(yrep, DUMMY_VAR__);
            current_statement_begin__ = 136;
            validate_non_negative_index("fitted", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> fitted(n);
            stan::math::initialize(fitted, DUMMY_VAR__);
            stan::math::fill(fitted, DUMMY_VAR__);
            current_statement_begin__ = 137;
            validate_non_negative_index("esf", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> esf(n);
            stan::math::initialize(esf, DUMMY_VAR__);
            stan::math::fill(esf, DUMMY_VAR__);
            current_statement_begin__ = 138;
            validate_non_negative_index("residual", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> residual(n);
            stan::math::initialize(residual, DUMMY_VAR__);
            stan::math::fill(residual, DUMMY_VAR__);
            current_statement_begin__ = 139;
            validate_non_negative_index("log_lik", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(n);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            current_statement_begin__ = 140;
            validate_non_negative_index("alpha_re", "n_ids", n_ids);
            Eigen::Matrix<double, Eigen::Dynamic, 1> alpha_re(n_ids);
            stan::math::initialize(alpha_re, DUMMY_VAR__);
            stan::math::fill(alpha_re, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 141;
            if (as_bool(has_re)) {
                current_statement_begin__ = 142;
                for (int i = 1; i <= n_ids; ++i) {
                    current_statement_begin__ = 143;
                    stan::model::assign(alpha_re, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (get_base1(alpha_tau, has_re, "alpha_tau", 1) * get_base1(alpha_re_tilde, i, "alpha_re_tilde", 1)), 
                                "assigning variable alpha_re");
                }
            }
            current_statement_begin__ = 146;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 147;
                stan::model::assign(fitted, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            stan::math::exp(get_base1(f, i, "f", 1)), 
                            "assigning variable fitted");
                current_statement_begin__ = 148;
                stan::model::assign(residual, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (get_base1(fitted, i, "fitted", 1) - get_base1(y, i, "y", 1)), 
                            "assigning variable residual");
                current_statement_begin__ = 149;
                stan::model::assign(esf, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            multiply(get_base1(EV, i, "EV", 1), beta_ev), 
                            "assigning variable esf");
                current_statement_begin__ = 150;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            poisson_log_log(get_base1(y, i, "y", 1), get_base1(f, i, "f", 1)), 
                            "assigning variable log_lik");
                current_statement_begin__ = 151;
                if (as_bool(logical_gt(get_base1(f, i, "f", 1), 20))) {
                    current_statement_begin__ = 152;
                    if (pstream__) {
                        stan_print(pstream__,"f[i] too large (>20) for poisson_log_rng");
                        *pstream__ << std::endl;
                    }
                    current_statement_begin__ = 153;
                    stan::model::assign(yrep, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                -(1), 
                                "assigning variable yrep");
                } else {
                    current_statement_begin__ = 155;
                    stan::model::assign(yrep, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                poisson_log_rng(get_base1(f, i, "f", 1), base_rng__), 
                                "assigning variable yrep");
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 135;
            size_t yrep_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < yrep_j_1_max__; ++j_1__) {
                vars__.push_back(yrep(j_1__));
            }
            current_statement_begin__ = 136;
            size_t fitted_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < fitted_j_1_max__; ++j_1__) {
                vars__.push_back(fitted(j_1__));
            }
            current_statement_begin__ = 137;
            size_t esf_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < esf_j_1_max__; ++j_1__) {
                vars__.push_back(esf(j_1__));
            }
            current_statement_begin__ = 138;
            size_t residual_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < residual_j_1_max__; ++j_1__) {
                vars__.push_back(residual(j_1__));
            }
            current_statement_begin__ = 139;
            size_t log_lik_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
            current_statement_begin__ = 140;
            size_t alpha_re_j_1_max__ = n_ids;
            for (size_t j_1__ = 0; j_1__ < alpha_re_j_1_max__; ++j_1__) {
                vars__.push_back(alpha_re(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_esf_count";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "aux1_global";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "aux2_global";
        param_names__.push_back(param_name_stream__.str());
        size_t aux1_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux1_local_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aux1_local" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aux2_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux2_local_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aux2_local" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "caux";
        param_names__.push_back(param_name_stream__.str());
        size_t z_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < z_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "z" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "intercept";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_tilde_j_1_max__ = dx;
        for (size_t j_1__ = 0; j_1__ < beta_tilde_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_tilde" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_re_tilde_j_1_max__ = n_ids;
        for (size_t j_1__ = 0; j_1__ < alpha_re_tilde_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha_re_tilde" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_tau_k_0_max__ = has_re;
        for (size_t k_0__ = 0; k_0__ < alpha_tau_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha_tau" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t nu_k_0_max__ = is_student;
        for (size_t k_0__ = 0; k_0__ < nu_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nu" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_k_0_max__ = has_sigma;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t f_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "f" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_j_1_max__ = dx;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_ev_j_1_max__ = dev;
            for (size_t j_1__ = 0; j_1__ < beta_ev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_ev" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "error_scale";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t yrep_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < yrep_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "yrep" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t fitted_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < fitted_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "fitted" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t esf_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < esf_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "esf" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t residual_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < residual_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "residual" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_re_j_1_max__ = n_ids;
        for (size_t j_1__ = 0; j_1__ < alpha_re_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha_re" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "aux1_global";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "aux2_global";
        param_names__.push_back(param_name_stream__.str());
        size_t aux1_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux1_local_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aux1_local" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t aux2_local_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < aux2_local_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "aux2_local" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "caux";
        param_names__.push_back(param_name_stream__.str());
        size_t z_j_1_max__ = dev;
        for (size_t j_1__ = 0; j_1__ < z_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "z" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "intercept";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_tilde_j_1_max__ = dx;
        for (size_t j_1__ = 0; j_1__ < beta_tilde_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_tilde" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_re_tilde_j_1_max__ = n_ids;
        for (size_t j_1__ = 0; j_1__ < alpha_re_tilde_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha_re_tilde" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_tau_k_0_max__ = has_re;
        for (size_t k_0__ = 0; k_0__ < alpha_tau_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha_tau" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t nu_k_0_max__ = is_student;
        for (size_t k_0__ = 0; k_0__ < nu_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nu" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_k_0_max__ = has_sigma;
        for (size_t k_0__ = 0; k_0__ < sigma_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t f_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < f_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "f" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_j_1_max__ = dx;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_ev_j_1_max__ = dev;
            for (size_t j_1__ = 0; j_1__ < beta_ev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_ev" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "error_scale";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t yrep_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < yrep_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "yrep" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t fitted_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < fitted_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "fitted" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t esf_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < esf_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "esf" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t residual_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < residual_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "residual" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_re_j_1_max__ = n_ids;
        for (size_t j_1__ = 0; j_1__ < alpha_re_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha_re" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_esf_count_namespace::model_esf_count stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
